# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.model_api import ModelApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestModelApi(unittest.TestCase):
    """ModelApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.model_api.ModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_model(self):
        """Test case for create_model

        Add a new model  # noqa: E501
        """
        pass

    def test_get_model(self):
        """Test case for get_model

        Get model by its ID  # noqa: E501
        """
        pass

    def test_get_models(self):
        """Test case for get_models

        Get all models  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
