# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.query_api import QueryApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.query_api.QueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_query_by_project_and_id(self):
        """Test case for delete_query_by_project_and_id

        Delete query by project and ID  # noqa: E501
        """
        pass

    def test_get_queries_by_project(self):
        """Test case for get_queries_by_project

        Get queries by project  # noqa: E501
        """
        pass

    def test_get_query_by_project_and_id(self):
        """Test case for get_query_by_project_and_id

        Get query by project and ID  # noqa: E501
        """
        pass

    def test_get_query_results_by_project_id_query(self):
        """Test case for get_query_results_by_project_id_query

        Get query results by project and query definition  # noqa: E501
        """
        pass

    def test_get_query_results_by_project_id_query_id(self):
        """Test case for get_query_results_by_project_id_query_id

        Get query results by project and query  # noqa: E501
        """
        pass

    def test_get_query_results_by_project_id_query_post(self):
        """Test case for get_query_results_by_project_id_query_post

        Get query results by project and query definition via POST  # noqa: E501
        """
        pass

    def test_post_query_by_project(self):
        """Test case for post_query_by_project

        Create query by project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
