# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.branch_api import BranchApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestBranchApi(unittest.TestCase):
    """BranchApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.branch_api.BranchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_branches_by_project(self):
        """Test case for get_branches_by_project

        Get branches by project  # noqa: E501
        """
        pass

    def test_get_branches_by_project_and_id(self):
        """Test case for get_branches_by_project_and_id

        Get branch by project and ID  # noqa: E501
        """
        pass

    def test_post_branch_by_project(self):
        """Test case for post_branch_by_project

        Create branch by project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
