# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.element_api import ElementApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestElementApi(unittest.TestCase):
    """ElementApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.element_api.ElementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_element_by_project_commit_id(self):
        """Test case for get_element_by_project_commit_id

        Get element by project, commit and ID  # noqa: E501
        """
        pass

    def test_get_elements_by_project_commit(self):
        """Test case for get_elements_by_project_commit

        Get elements by project and commit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
