# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.project_api import ProjectApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_project(self):
        """Test case for create_project

        Add a new project  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Get project by its ID  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Get all projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
