# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.relationship_api import RelationshipApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestRelationshipApi(unittest.TestCase):
    """RelationshipApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.relationship_api.RelationshipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_relationships_by_project_commit_related_element(self):
        """Test case for get_relationships_by_project_commit_related_element

        Get relationships by project, commit, and related element  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
