# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.tag_api import TagApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.tag_api.TagApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tag_by_project_and_id(self):
        """Test case for delete_tag_by_project_and_id

        Delete tag by project and ID  # noqa: E501
        """
        pass

    def test_get_tag_by_project_and_id(self):
        """Test case for get_tag_by_project_and_id

        Get tag by project and ID  # noqa: E501
        """
        pass

    def test_get_tags_by_project(self):
        """Test case for get_tags_by_project

        Get tags by project  # noqa: E501
        """
        pass

    def test_post_tag_by_project(self):
        """Test case for post_tag_by_project

        Create tag by project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
