# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.models.element import Element  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestElement(unittest.TestCase):
    """Element unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testElement(self):
        """Test Element"""
        # FIXME: construct object with mandatory attributes with example values
        # model = sysml_v2_api_client.models.element.Element()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
