# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.commit_api import CommitApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestCommitApi(unittest.TestCase):
    """CommitApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.commit_api.CommitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_commit_by_project_and_id(self):
        """Test case for get_commit_by_project_and_id

        Get commit by project and ID  # noqa: E501
        """
        pass

    def test_get_commits_by_project(self):
        """Test case for get_commits_by_project

        Get commits by project  # noqa: E501
        """
        pass

    def test_post_commit_by_project(self):
        """Test case for post_commit_by_project

        Create commit by project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
