# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import sysml_v2_api_client
from sysml_v2_api_client.api.element_api import ElementApi  # noqa: E501
from sysml_v2_api_client.rest import ApiException


class TestElementApi(unittest.TestCase):
    """ElementApi unit test stubs"""

    def setUp(self):
        self.api = sysml_v2_api_client.api.element_api.ElementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_element(self):
        """Test case for create_element

        Add a new element  # noqa: E501
        """
        pass

    def test_get_element(self):
        """Test case for get_element

        Get element by its ID  # noqa: E501
        """
        pass

    def test_get_elements(self):
        """Test case for get_elements

        Get all elements  # noqa: E501
        """
        pass

    def test_get_elements_in_model(self):
        """Test case for get_elements_in_model

        Get all elements in the model  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
