# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Element(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'identifier': 'str',
        'name': 'str',
        'description': 'str',
        'parent_model': 'str',
        'type': 'str'
    }

    attribute_map = {
        'identifier': 'identifier',
        'name': 'name',
        'description': 'description',
        'parent_model': 'parent_model',
        'type': 'type'
    }

    def __init__(self, identifier=None, name=None, description=None, parent_model=None, type=None):  # noqa: E501
        """Element - a model defined in OpenAPI"""  # noqa: E501

        self._identifier = None
        self._name = None
        self._description = None
        self._parent_model = None
        self._type = None
        self.discriminator = None

        if identifier is not None:
            self.identifier = identifier
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if parent_model is not None:
            self.parent_model = parent_model
        if type is not None:
            self.type = type

    @property
    def identifier(self):
        """Gets the identifier of this Element.  # noqa: E501


        :return: The identifier of this Element.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this Element.


        :param identifier: The identifier of this Element.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def name(self):
        """Gets the name of this Element.  # noqa: E501


        :return: The name of this Element.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Element.


        :param name: The name of this Element.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this Element.  # noqa: E501


        :return: The description of this Element.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Element.


        :param description: The description of this Element.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def parent_model(self):
        """Gets the parent_model of this Element.  # noqa: E501


        :return: The parent_model of this Element.  # noqa: E501
        :rtype: str
        """
        return self._parent_model

    @parent_model.setter
    def parent_model(self, parent_model):
        """Sets the parent_model of this Element.


        :param parent_model: The parent_model of this Element.  # noqa: E501
        :type: str
        """

        self._parent_model = parent_model

    @property
    def type(self):
        """Gets the type of this Element.  # noqa: E501


        :return: The type of this Element.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Element.


        :param type: The type of this Element.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Element):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
