# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sysml_v2_api_client.configuration import Configuration


class PrimitiveConstraint(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'inverse': 'bool',
        '_property': 'str',
        'value': 'str',
        'operator': 'str'
    }

    attribute_map = {
        'type': '@type',
        'inverse': 'inverse',
        '_property': 'property',
        'value': 'value',
        'operator': 'operator'
    }

    def __init__(self, type=None, inverse=None, _property=None, value=None, operator=None, local_vars_configuration=None):  # noqa: E501
        """PrimitiveConstraint - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._inverse = None
        self.__property = None
        self._value = None
        self._operator = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if inverse is not None:
            self.inverse = inverse
        if _property is not None:
            self._property = _property
        if value is not None:
            self.value = value
        if operator is not None:
            self.operator = operator

    @property
    def type(self):
        """Gets the type of this PrimitiveConstraint.  # noqa: E501


        :return: The type of this PrimitiveConstraint.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PrimitiveConstraint.


        :param type: The type of this PrimitiveConstraint.  # noqa: E501
        :type: str
        """
        allowed_values = ["PrimitiveConstraint"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def inverse(self):
        """Gets the inverse of this PrimitiveConstraint.  # noqa: E501


        :return: The inverse of this PrimitiveConstraint.  # noqa: E501
        :rtype: bool
        """
        return self._inverse

    @inverse.setter
    def inverse(self, inverse):
        """Sets the inverse of this PrimitiveConstraint.


        :param inverse: The inverse of this PrimitiveConstraint.  # noqa: E501
        :type: bool
        """

        self._inverse = inverse

    @property
    def _property(self):
        """Gets the _property of this PrimitiveConstraint.  # noqa: E501


        :return: The _property of this PrimitiveConstraint.  # noqa: E501
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """Sets the _property of this PrimitiveConstraint.


        :param _property: The _property of this PrimitiveConstraint.  # noqa: E501
        :type: str
        """

        self.__property = _property

    @property
    def value(self):
        """Gets the value of this PrimitiveConstraint.  # noqa: E501


        :return: The value of this PrimitiveConstraint.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PrimitiveConstraint.


        :param value: The value of this PrimitiveConstraint.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def operator(self):
        """Gets the operator of this PrimitiveConstraint.  # noqa: E501


        :return: The operator of this PrimitiveConstraint.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this PrimitiveConstraint.


        :param operator: The operator of this PrimitiveConstraint.  # noqa: E501
        :type: str
        """
        allowed_values = ["=", ">", "<"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and operator not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `operator` ({0}), must be one of {1}"  # noqa: E501
                .format(operator, allowed_values)
            )

        self._operator = operator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PrimitiveConstraint):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PrimitiveConstraint):
            return True

        return self.to_dict() != other.to_dict()
