# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Relationship(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'source_element_role': 'str',
        'source_element': 'str',
        'target_element_role': 'str',
        'target_element': 'str'
    }

    attribute_map = {
        'source_element_role': 'source_element_role',
        'source_element': 'source_element',
        'target_element_role': 'target_element_role',
        'target_element': 'target_element'
    }

    def __init__(self, source_element_role=None, source_element=None, target_element_role=None, target_element=None):  # noqa: E501
        """Relationship - a model defined in OpenAPI"""  # noqa: E501

        self._source_element_role = None
        self._source_element = None
        self._target_element_role = None
        self._target_element = None
        self.discriminator = None

        if source_element_role is not None:
            self.source_element_role = source_element_role
        if source_element is not None:
            self.source_element = source_element
        if target_element_role is not None:
            self.target_element_role = target_element_role
        if target_element is not None:
            self.target_element = target_element

    @property
    def source_element_role(self):
        """Gets the source_element_role of this Relationship.  # noqa: E501


        :return: The source_element_role of this Relationship.  # noqa: E501
        :rtype: str
        """
        return self._source_element_role

    @source_element_role.setter
    def source_element_role(self, source_element_role):
        """Sets the source_element_role of this Relationship.


        :param source_element_role: The source_element_role of this Relationship.  # noqa: E501
        :type: str
        """

        self._source_element_role = source_element_role

    @property
    def source_element(self):
        """Gets the source_element of this Relationship.  # noqa: E501


        :return: The source_element of this Relationship.  # noqa: E501
        :rtype: str
        """
        return self._source_element

    @source_element.setter
    def source_element(self, source_element):
        """Sets the source_element of this Relationship.


        :param source_element: The source_element of this Relationship.  # noqa: E501
        :type: str
        """

        self._source_element = source_element

    @property
    def target_element_role(self):
        """Gets the target_element_role of this Relationship.  # noqa: E501


        :return: The target_element_role of this Relationship.  # noqa: E501
        :rtype: str
        """
        return self._target_element_role

    @target_element_role.setter
    def target_element_role(self, target_element_role):
        """Sets the target_element_role of this Relationship.


        :param target_element_role: The target_element_role of this Relationship.  # noqa: E501
        :type: str
        """

        self._target_element_role = target_element_role

    @property
    def target_element(self):
        """Gets the target_element of this Relationship.  # noqa: E501


        :return: The target_element of this Relationship.  # noqa: E501
        :rtype: str
        """
        return self._target_element

    @target_element.setter
    def target_element(self, target_element):
        """Sets the target_element of this Relationship.


        :param target_element: The target_element of this Relationship.  # noqa: E501
        :type: str
        """

        self._target_element = target_element

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Relationship):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
