# coding: utf-8

"""
    SysML v2 API and Services

    REST/HTTP binding (PSM) for the SysML v2 standard API.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Relationship(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'containing_project': 'Identified',
        'identifier': 'str',
        'source': 'list[Identified]',
        'target': 'list[Identified]'
    }

    attribute_map = {
        'type': '@type',
        'containing_project': 'containingProject',
        'identifier': 'identifier',
        'source': 'source',
        'target': 'target'
    }

    def __init__(self, type=None, containing_project=None, identifier=None, source=None, target=None):  # noqa: E501
        """Relationship - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._containing_project = None
        self._identifier = None
        self._source = None
        self._target = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if containing_project is not None:
            self.containing_project = containing_project
        if identifier is not None:
            self.identifier = identifier
        if source is not None:
            self.source = source
        if target is not None:
            self.target = target

    @property
    def type(self):
        """Gets the type of this Relationship.  # noqa: E501


        :return: The type of this Relationship.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Relationship.


        :param type: The type of this Relationship.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def containing_project(self):
        """Gets the containing_project of this Relationship.  # noqa: E501


        :return: The containing_project of this Relationship.  # noqa: E501
        :rtype: Identified
        """
        return self._containing_project

    @containing_project.setter
    def containing_project(self, containing_project):
        """Sets the containing_project of this Relationship.


        :param containing_project: The containing_project of this Relationship.  # noqa: E501
        :type: Identified
        """

        self._containing_project = containing_project

    @property
    def identifier(self):
        """Gets the identifier of this Relationship.  # noqa: E501


        :return: The identifier of this Relationship.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this Relationship.


        :param identifier: The identifier of this Relationship.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def source(self):
        """Gets the source of this Relationship.  # noqa: E501


        :return: The source of this Relationship.  # noqa: E501
        :rtype: list[Identified]
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Relationship.


        :param source: The source of this Relationship.  # noqa: E501
        :type: list[Identified]
        """

        self._source = source

    @property
    def target(self):
        """Gets the target of this Relationship.  # noqa: E501


        :return: The target of this Relationship.  # noqa: E501
        :rtype: list[Identified]
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this Relationship.


        :param target: The target of this Relationship.  # noqa: E501
        :type: list[Identified]
        """

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Relationship):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
